// Generated by listennotes/devtools/api-sdks/sync.py swift. Do not edit.
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

extension Client {
    /// Full-text search (GET /search)
    public func search(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/search", method: "GET",
                          pathNames: [], queryNames: ["q", "sort_by_date", "type", "offset", "len_min", "len_max", "episode_count_min", "episode_count_max", "update_freq_min", "update_freq_max", "genre_ids", "published_before", "published_after", "only_in", "language", "region", "ocid", "ncid", "safe_mode", "unique_podcasts", "interviews_only", "sponsored_only", "page_size"], parameters: parameters)
    }

    /// Full-text search (GET /search)
    @discardableResult
    public func search(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/search", method: "GET",
                pathNames: [], queryNames: ["q", "sort_by_date", "type", "offset", "len_min", "len_max", "episode_count_min", "episode_count_max", "update_freq_min", "update_freq_max", "genre_ids", "published_before", "published_after", "only_in", "language", "region", "ocid", "ncid", "safe_mode", "unique_podcasts", "interviews_only", "sponsored_only", "page_size"], parameters: parameters, completion: completion)
    }

    /// Typeahead search (GET /typeahead)
    public func typeahead(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/typeahead", method: "GET",
                          pathNames: [], queryNames: ["q", "show_podcasts", "show_genres", "safe_mode"], parameters: parameters)
    }

    /// Typeahead search (GET /typeahead)
    @discardableResult
    public func typeahead(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/typeahead", method: "GET",
                pathNames: [], queryNames: ["q", "show_podcasts", "show_genres", "safe_mode"], parameters: parameters, completion: completion)
    }

    /// Find individual episodes by searching for their titles (GET /search_episode_titles)
    public func searchEpisodeTitles(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/search_episode_titles", method: "GET",
                          pathNames: [], queryNames: ["q", "podcast_id", "podcast_id_type"], parameters: parameters)
    }

    /// Find individual episodes by searching for their titles (GET /search_episode_titles)
    @discardableResult
    public func searchEpisodeTitles(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/search_episode_titles", method: "GET",
                pathNames: [], queryNames: ["q", "podcast_id", "podcast_id_type"], parameters: parameters, completion: completion)
    }

    /// Spell check on a search term (GET /spellcheck)
    public func spellcheck(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/spellcheck", method: "GET",
                          pathNames: [], queryNames: ["q"], parameters: parameters)
    }

    /// Spell check on a search term (GET /spellcheck)
    @discardableResult
    public func spellcheck(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/spellcheck", method: "GET",
                pathNames: [], queryNames: ["q"], parameters: parameters, completion: completion)
    }

    /// Fetch related search terms (GET /related_searches)
    public func fetchRelatedSearches(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/related_searches", method: "GET",
                          pathNames: [], queryNames: ["q"], parameters: parameters)
    }

    /// Fetch related search terms (GET /related_searches)
    @discardableResult
    public func fetchRelatedSearches(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/related_searches", method: "GET",
                pathNames: [], queryNames: ["q"], parameters: parameters, completion: completion)
    }

    /// Fetch trending search terms (GET /trending_searches)
    public func fetchTrendingSearches(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/trending_searches", method: "GET",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Fetch trending search terms (GET /trending_searches)
    @discardableResult
    public func fetchTrendingSearches(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/trending_searches", method: "GET",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch a list of best podcasts by genre (GET /best_podcasts)
    public func fetchBestPodcasts(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/best_podcasts", method: "GET",
                          pathNames: [], queryNames: ["genre_id", "page", "region", "publisher_region", "language", "sort", "safe_mode"], parameters: parameters)
    }

    /// Fetch a list of best podcasts by genre (GET /best_podcasts)
    @discardableResult
    public func fetchBestPodcasts(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/best_podcasts", method: "GET",
                pathNames: [], queryNames: ["genre_id", "page", "region", "publisher_region", "language", "sort", "safe_mode"], parameters: parameters, completion: completion)
    }

    /// Fetch detailed meta data and episodes for a podcast by id (GET /podcasts/{id})
    public func fetchPodcastById(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/podcasts/{id}", method: "GET",
                          pathNames: ["id"], queryNames: ["next_episode_pub_date", "sort"], parameters: parameters)
    }

    /// Fetch detailed meta data and episodes for a podcast by id (GET /podcasts/{id})
    @discardableResult
    public func fetchPodcastById(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/podcasts/{id}", method: "GET",
                pathNames: ["id"], queryNames: ["next_episode_pub_date", "sort"], parameters: parameters, completion: completion)
    }

    /// Request to delete a podcast (DELETE /podcasts/{id})
    public func deletePodcast(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/podcasts/{id}", method: "DELETE",
                          pathNames: ["id"], queryNames: ["reason"], parameters: parameters)
    }

    /// Request to delete a podcast (DELETE /podcasts/{id})
    @discardableResult
    public func deletePodcast(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/podcasts/{id}", method: "DELETE",
                pathNames: ["id"], queryNames: ["reason"], parameters: parameters, completion: completion)
    }

    /// Fetch detailed meta data for an episode by id (GET /episodes/{id})
    public func fetchEpisodeById(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/episodes/{id}", method: "GET",
                          pathNames: ["id"], queryNames: ["show_transcript"], parameters: parameters)
    }

    /// Fetch detailed meta data for an episode by id (GET /episodes/{id})
    @discardableResult
    public func fetchEpisodeById(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/episodes/{id}", method: "GET",
                pathNames: ["id"], queryNames: ["show_transcript"], parameters: parameters, completion: completion)
    }

    /// Batch fetch basic meta data for episodes (POST /episodes)
    public func batchFetchEpisodes(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/episodes", method: "POST",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Batch fetch basic meta data for episodes (POST /episodes)
    @discardableResult
    public func batchFetchEpisodes(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/episodes", method: "POST",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Batch fetch basic meta data for podcasts (POST /podcasts)
    public func batchFetchPodcasts(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/podcasts", method: "POST",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Batch fetch basic meta data for podcasts (POST /podcasts)
    @discardableResult
    public func batchFetchPodcasts(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/podcasts", method: "POST",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch a curated list of podcasts by id (GET /curated_podcasts/{id})
    public func fetchCuratedPodcastsListById(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/curated_podcasts/{id}", method: "GET",
                          pathNames: ["id"], queryNames: [], parameters: parameters)
    }

    /// Fetch a curated list of podcasts by id (GET /curated_podcasts/{id})
    @discardableResult
    public func fetchCuratedPodcastsListById(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/curated_podcasts/{id}", method: "GET",
                pathNames: ["id"], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch a list of podcast genres (GET /genres)
    public func fetchPodcastGenres(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/genres", method: "GET",
                          pathNames: [], queryNames: ["top_level_only"], parameters: parameters)
    }

    /// Fetch a list of podcast genres (GET /genres)
    @discardableResult
    public func fetchPodcastGenres(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/genres", method: "GET",
                pathNames: [], queryNames: ["top_level_only"], parameters: parameters, completion: completion)
    }

    /// Fetch a list of supported countries/regions for best podcasts (GET /regions)
    public func fetchPodcastRegions(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/regions", method: "GET",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Fetch a list of supported countries/regions for best podcasts (GET /regions)
    @discardableResult
    public func fetchPodcastRegions(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/regions", method: "GET",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch a list of supported languages for podcasts (GET /languages)
    public func fetchPodcastLanguages(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/languages", method: "GET",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Fetch a list of supported languages for podcasts (GET /languages)
    @discardableResult
    public func fetchPodcastLanguages(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/languages", method: "GET",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch a random podcast episode (GET /just_listen)
    public func justListen(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/just_listen", method: "GET",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Fetch a random podcast episode (GET /just_listen)
    @discardableResult
    public func justListen(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/just_listen", method: "GET",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch curated lists of podcasts (GET /curated_podcasts)
    public func fetchCuratedPodcastsLists(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/curated_podcasts", method: "GET",
                          pathNames: [], queryNames: ["page"], parameters: parameters)
    }

    /// Fetch curated lists of podcasts (GET /curated_podcasts)
    @discardableResult
    public func fetchCuratedPodcastsLists(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/curated_podcasts", method: "GET",
                pathNames: [], queryNames: ["page"], parameters: parameters, completion: completion)
    }

    /// Fetch recommendations for a podcast (GET /podcasts/{id}/recommendations)
    public func fetchRecommendationsForPodcast(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/podcasts/{id}/recommendations", method: "GET",
                          pathNames: ["id"], queryNames: ["safe_mode"], parameters: parameters)
    }

    /// Fetch recommendations for a podcast (GET /podcasts/{id}/recommendations)
    @discardableResult
    public func fetchRecommendationsForPodcast(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/podcasts/{id}/recommendations", method: "GET",
                pathNames: ["id"], queryNames: ["safe_mode"], parameters: parameters, completion: completion)
    }

    /// Fetch recommendations for an episode (GET /episodes/{id}/recommendations)
    public func fetchRecommendationsForEpisode(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/episodes/{id}/recommendations", method: "GET",
                          pathNames: ["id"], queryNames: ["safe_mode"], parameters: parameters)
    }

    /// Fetch recommendations for an episode (GET /episodes/{id}/recommendations)
    @discardableResult
    public func fetchRecommendationsForEpisode(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/episodes/{id}/recommendations", method: "GET",
                pathNames: ["id"], queryNames: ["safe_mode"], parameters: parameters, completion: completion)
    }

    /// Submit a podcast to Listen Notes database (POST /podcasts/submit)
    public func submitPodcast(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/podcasts/submit", method: "POST",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Submit a podcast to Listen Notes database (POST /podcasts/submit)
    @discardableResult
    public func submitPodcast(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/podcasts/submit", method: "POST",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch a playlist's info and items (i.e., episodes or podcasts). (GET /playlists/{id})
    public func fetchPlaylistById(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/playlists/{id}", method: "GET",
                          pathNames: ["id"], queryNames: ["type", "last_timestamp_ms", "sort"], parameters: parameters)
    }

    /// Fetch a playlist's info and items (i.e., episodes or podcasts). (GET /playlists/{id})
    @discardableResult
    public func fetchPlaylistById(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/playlists/{id}", method: "GET",
                pathNames: ["id"], queryNames: ["type", "last_timestamp_ms", "sort"], parameters: parameters, completion: completion)
    }

    /// Fetch a list of your playlists. (GET /playlists)
    public func fetchMyPlaylists(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/playlists", method: "GET",
                          pathNames: [], queryNames: ["sort", "page"], parameters: parameters)
    }

    /// Fetch a list of your playlists. (GET /playlists)
    @discardableResult
    public func fetchMyPlaylists(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/playlists", method: "GET",
                pathNames: [], queryNames: ["sort", "page"], parameters: parameters, completion: completion)
    }

    /// Fetch audience demographics for a podcast (GET /podcasts/{id}/audience)
    public func fetchAudienceForPodcast(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/podcasts/{id}/audience", method: "GET",
                          pathNames: ["id"], queryNames: [], parameters: parameters)
    }

    /// Fetch audience demographics for a podcast (GET /podcasts/{id}/audience)
    @discardableResult
    public func fetchAudienceForPodcast(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/podcasts/{id}/audience", method: "GET",
                pathNames: ["id"], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Fetch podcasts by a publisher's domain name (GET /podcasts/domains/{domain_name})
    public func fetchPodcastsByDomain(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/podcasts/domains/{domain_name}", method: "GET",
                          pathNames: ["domain_name"], queryNames: ["page"], parameters: parameters)
    }

    /// Fetch podcasts by a publisher's domain name (GET /podcasts/domains/{domain_name})
    @discardableResult
    public func fetchPodcastsByDomain(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/podcasts/domains/{domain_name}", method: "GET",
                pathNames: ["domain_name"], queryNames: ["page"], parameters: parameters, completion: completion)
    }

    /// Create a playlist. (POST /playlists)
    public func createPlaylist(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/playlists", method: "POST",
                          pathNames: [], queryNames: [], parameters: parameters)
    }

    /// Create a playlist. (POST /playlists)
    @discardableResult
    public func createPlaylist(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/playlists", method: "POST",
                pathNames: [], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Update playlist metadata. (PUT /playlists/{id})
    public func updatePlaylist(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/playlists/{id}", method: "PUT",
                          pathNames: ["id"], queryNames: [], parameters: parameters)
    }

    /// Update playlist metadata. (PUT /playlists/{id})
    @discardableResult
    public func updatePlaylist(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/playlists/{id}", method: "PUT",
                pathNames: ["id"], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Add an episode or podcast to a playlist. (POST /playlists/{id}/items)
    public func addPlaylistItem(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/playlists/{id}/items", method: "POST",
                          pathNames: ["id"], queryNames: [], parameters: parameters)
    }

    /// Add an episode or podcast to a playlist. (POST /playlists/{id}/items)
    @discardableResult
    public func addPlaylistItem(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/playlists/{id}/items", method: "POST",
                pathNames: ["id"], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Remove an item from a playlist. (DELETE /playlists/{id}/items/{item_id})
    public func deletePlaylistItem(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/playlists/{id}/items/{item_id}", method: "DELETE",
                          pathNames: ["id", "item_id"], queryNames: [], parameters: parameters)
    }

    /// Remove an item from a playlist. (DELETE /playlists/{id}/items/{item_id})
    @discardableResult
    public func deletePlaylistItem(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/playlists/{id}/items/{item_id}", method: "DELETE",
                pathNames: ["id", "item_id"], queryNames: [], parameters: parameters, completion: completion)
    }

    /// Update notes for a playlist item. (PUT /playlists/{id}/items/{item_id})
    public func updatePlaylistItemNotes(parameters: [String: String] = [:]) async throws -> ApiResponse {
        try await request(path: "/playlists/{id}/items/{item_id}", method: "PUT",
                          pathNames: ["id", "item_id"], queryNames: [], parameters: parameters)
    }

    /// Update notes for a playlist item. (PUT /playlists/{id}/items/{item_id})
    @discardableResult
    public func updatePlaylistItemNotes(parameters: [String: String] = [:],
                     completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
        request(path: "/playlists/{id}/items/{item_id}", method: "PUT",
                pathNames: ["id", "item_id"], queryNames: [], parameters: parameters, completion: completion)
    }

}
