// Generated by listennotes/devtools/api-sdks/sync.py swift. Do not edit.
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import PodcastAPI

func callMethod(_ operation: String, client: Client, parameters: [String: String]) async throws -> ApiResponse {
    switch operation {
    case "search":
        return try await client.search(parameters: parameters)
    case "typeahead":
        return try await client.typeahead(parameters: parameters)
    case "searchEpisodeTitles":
        return try await client.searchEpisodeTitles(parameters: parameters)
    case "spellcheck":
        return try await client.spellcheck(parameters: parameters)
    case "getRelatedSearches":
        return try await client.fetchRelatedSearches(parameters: parameters)
    case "getTrendingSearches":
        return try await client.fetchTrendingSearches(parameters: parameters)
    case "getBestPodcasts":
        return try await client.fetchBestPodcasts(parameters: parameters)
    case "getPodcastById":
        return try await client.fetchPodcastById(parameters: parameters)
    case "deletePodcastById":
        return try await client.deletePodcast(parameters: parameters)
    case "getEpisodeById":
        return try await client.fetchEpisodeById(parameters: parameters)
    case "getEpisodesInBatch":
        return try await client.batchFetchEpisodes(parameters: parameters)
    case "getPodcastsInBatch":
        return try await client.batchFetchPodcasts(parameters: parameters)
    case "getCuratedPodcastById":
        return try await client.fetchCuratedPodcastsListById(parameters: parameters)
    case "getGenres":
        return try await client.fetchPodcastGenres(parameters: parameters)
    case "getRegions":
        return try await client.fetchPodcastRegions(parameters: parameters)
    case "getLanguages":
        return try await client.fetchPodcastLanguages(parameters: parameters)
    case "justListen":
        return try await client.justListen(parameters: parameters)
    case "getCuratedPodcasts":
        return try await client.fetchCuratedPodcastsLists(parameters: parameters)
    case "getPodcastRecommendations":
        return try await client.fetchRecommendationsForPodcast(parameters: parameters)
    case "getEpisodeRecommendations":
        return try await client.fetchRecommendationsForEpisode(parameters: parameters)
    case "submitPodcast":
        return try await client.submitPodcast(parameters: parameters)
    case "getPlaylistById":
        return try await client.fetchPlaylistById(parameters: parameters)
    case "getPlaylists":
        return try await client.fetchMyPlaylists(parameters: parameters)
    case "getPodcastAudience":
        return try await client.fetchAudienceForPodcast(parameters: parameters)
    case "getPodcastsByDomainName":
        return try await client.fetchPodcastsByDomain(parameters: parameters)
    case "createPlaylist":
        return try await client.createPlaylist(parameters: parameters)
    case "updatePlaylist":
        return try await client.updatePlaylist(parameters: parameters)
    case "deletePlaylist":
        return try await client.deletePlaylist(parameters: parameters)
    case "addPlaylistItem":
        return try await client.addPlaylistItem(parameters: parameters)
    case "deletePlaylistItem":
        return try await client.deletePlaylistItem(parameters: parameters)
    case "updatePlaylistItemNotes":
        return try await client.updatePlaylistItemNotes(parameters: parameters)
    default: preconditionFailure("Unknown operation")
    }
}

@discardableResult
func callMethod(_ operation: String, client: Client, parameters: [String: String],
                completion: @escaping @Sendable (ApiResponse) -> Void) -> URLSessionDataTask? {
    switch operation {
    case "search":
        return client.search(parameters: parameters, completion: completion)
    case "typeahead":
        return client.typeahead(parameters: parameters, completion: completion)
    case "searchEpisodeTitles":
        return client.searchEpisodeTitles(parameters: parameters, completion: completion)
    case "spellcheck":
        return client.spellcheck(parameters: parameters, completion: completion)
    case "getRelatedSearches":
        return client.fetchRelatedSearches(parameters: parameters, completion: completion)
    case "getTrendingSearches":
        return client.fetchTrendingSearches(parameters: parameters, completion: completion)
    case "getBestPodcasts":
        return client.fetchBestPodcasts(parameters: parameters, completion: completion)
    case "getPodcastById":
        return client.fetchPodcastById(parameters: parameters, completion: completion)
    case "deletePodcastById":
        return client.deletePodcast(parameters: parameters, completion: completion)
    case "getEpisodeById":
        return client.fetchEpisodeById(parameters: parameters, completion: completion)
    case "getEpisodesInBatch":
        return client.batchFetchEpisodes(parameters: parameters, completion: completion)
    case "getPodcastsInBatch":
        return client.batchFetchPodcasts(parameters: parameters, completion: completion)
    case "getCuratedPodcastById":
        return client.fetchCuratedPodcastsListById(parameters: parameters, completion: completion)
    case "getGenres":
        return client.fetchPodcastGenres(parameters: parameters, completion: completion)
    case "getRegions":
        return client.fetchPodcastRegions(parameters: parameters, completion: completion)
    case "getLanguages":
        return client.fetchPodcastLanguages(parameters: parameters, completion: completion)
    case "justListen":
        return client.justListen(parameters: parameters, completion: completion)
    case "getCuratedPodcasts":
        return client.fetchCuratedPodcastsLists(parameters: parameters, completion: completion)
    case "getPodcastRecommendations":
        return client.fetchRecommendationsForPodcast(parameters: parameters, completion: completion)
    case "getEpisodeRecommendations":
        return client.fetchRecommendationsForEpisode(parameters: parameters, completion: completion)
    case "submitPodcast":
        return client.submitPodcast(parameters: parameters, completion: completion)
    case "getPlaylistById":
        return client.fetchPlaylistById(parameters: parameters, completion: completion)
    case "getPlaylists":
        return client.fetchMyPlaylists(parameters: parameters, completion: completion)
    case "getPodcastAudience":
        return client.fetchAudienceForPodcast(parameters: parameters, completion: completion)
    case "getPodcastsByDomainName":
        return client.fetchPodcastsByDomain(parameters: parameters, completion: completion)
    case "createPlaylist":
        return client.createPlaylist(parameters: parameters, completion: completion)
    case "updatePlaylist":
        return client.updatePlaylist(parameters: parameters, completion: completion)
    case "deletePlaylist":
        return client.deletePlaylist(parameters: parameters, completion: completion)
    case "addPlaylistItem":
        return client.addPlaylistItem(parameters: parameters, completion: completion)
    case "deletePlaylistItem":
        return client.deletePlaylistItem(parameters: parameters, completion: completion)
    case "updatePlaylistItemNotes":
        return client.updatePlaylistItemNotes(parameters: parameters, completion: completion)
    default: preconditionFailure("Unknown operation")
    }
}
